create table DbGeocoderResult (
    id bigint generated by default as identity,
    createdAt timestamp,
    modifiedAt timestamp,
    naturalKey varchar(32) not null unique,
    VERSION_NR bigint not null,
    cityName varchar(255),
    exact smallint not null,
    formattedAddressString varchar(255),
    lastAccess timestamp,
    lat double not null,
    lng double not null,
    normalizedAddressString varchar(255),
    street varchar(255),
    streetNr varchar(255),
    zip integer not null,
    primary key (id)
);