create table RunningDinnerPreference (
    id bigint generated by default as identity,
    createdAt timestamp,
    modifiedAt timestamp,
    naturalKey varchar(32) not null unique,
    VERSION_NR bigint not null,
    preferenceName varchar(255) not null,
    preferenceValue varchar(4096) not null,
    dinner_id bigint,
    primary key (id)
);

alter table RunningDinnerPreference 
    add constraint FK3C41F2ACF916B1ED 
    foreign key (dinner_id) 
    references RunningDinner;